### ISSUE TITLE
AttributeError: type object 'Meta' has no attribute 'valid_status_codes'

### ISSUE THREAD

**Issue by inglesp** [phalt/beckett#31]
When following the example in the docs, I get the following error:

```
Traceback (most recent call last):
  File "repro.py", line 27, in <module>
    c = MyClient()
  File "/Users/inglesp/src/phalt/beckett/beckett/clients.py", line 142, in __init__
    self.assign_resources(self.Meta.resources)
  File "/Users/inglesp/src/phalt/beckett/beckett/clients.py", line 157, in assign_resources
    self.assign_methods(resource)
  File "/Users/inglesp/src/phalt/beckett/beckett/clients.py", line 173, in assign_methods
    method.upper()
  File "/Users/inglesp/src/phalt/beckett/beckett/clients.py", line 191, in _assign_method
    valid_status_codes = resource_class.Meta.valid_status_codes
AttributeError: type object 'Meta' has no attribute 'valid_status_codes'```
```

I've seen this with Pythons 2.7.10 and 3.5.1.

My `repro.py` is below:

```
from beckett.resources import BaseResource
from beckett.clients import BaseClient

class Product(BaseResource):  
    class Meta:
        name = 'Product'
        identifier = 'slug'
        attributes = (
            'slug',
            'brand',
            'price',
            'images',
        )
        methods = (
            'get',
            'post',
        )

class MyClient(BaseClient):  
    class Meta:
        name = 'My API Client'
        base_url = 'https://myapi.com/api/'
        resources = (
            Product,
        )

c = MyClient()
```

**Comment by phalt** [comment]
@inglesp thanks for this, I've been able to reproduce it! I'll update the example so it works correctly.

**Comment by phalt** [comment]
The only instance I can see where this might be wrong is in the blog post, which has been updated.

Some attributes are not required in the `class Meta` declaration, but required the parent's Meta class to be inherited:

```
class Product(BaseResource):  
    class Meta(BaseResource.Meta):
```
